name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Restore packages
      run: nuget.exe restore Hikari.sln

    - name: MSBuild
      working-directory: .
      run: msbuild Hikari.sln

